### ISSUE TITLE
Экран Product Details

### ISSUE THREAD

**Issue by Glajik** [Glajik/diet-routine#86]
*Форма для добавления продукта в "отобранные", с настройкой веса/объема продукта*

## Todo
- [x] Верстка формы
- [x] Перерасчет калорий, и БЖУ
- [x] Добавление записи в коллекцию Journal, с пометкой isDraft
- [x] Отображать список продуктов в модальном окне по нажатию на соотв. иконку на экране Product Search
