### ISSUE TITLE
Экран Calculator

### ISSUE THREAD

**Issue by Glajik** [Glajik/diet-routine#90]
*Форма для расчета нормы*

## Todo
- [ ] Верстка формы
- [ ] Продумать, как использовать разные компоненты для разных типов данных
- [ ] См. пример в Telegram в настройках
- [ ] Обновлять профиль пользователя в Firestore
